name: fooocus_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/playstore.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/playstore.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/playstore.png"
environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.2
  replicate_json: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
